FROM node:alpine

WORKDIR /app

COPY ./package*.json .

RUN npm install
RUN npm install -D vitest jsdom @testing-library/react @testing-library/jest-dom

COPY ./ ./

EXPOSE 5173

CMD ["npm", "run" , "dev"]