version: 2.1

jobs:
  test:
    machine: true

    steps:
      - checkout

      - run:
          name : Build Docker image
          command: |
            docker build -t nawnwa/vite-react-app-circleci \
              -f Dockerfile.dev .
      
      - run:
          name: Run Vitest tests
          command: |
            docker run nawnwa/vite-react-app-circleci \
              npm run test -- --run
      

  deploy-aws:
    machine: true

    steps:
      - checkout

      - run:
          name: Install EB CLI
          command: |
            pip install --user awsebcli
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV

      - run:
          name: Configure AWS credentials
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

      - run:
          name: Initialize EB app context
          command: |
            eb init react-vite-app \
              --platform docker \
              --region $AWS_REGION || true
        
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb use React-vite-docker-env
            eb deploy

workflows:
  test-then-deploy-workflow:
    jobs:
      - test
      - deploy-aws:
          requires:
            - test